- name: Ansible Jobs Create
  hosts: localhost
  tasks:
    - name: Create Jenkins Job
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: test1
        password: Alphaomega4315
        url: http://172.31.37.116:8080
        user: admin
